FROM node:20.18.1-alpine
ARG DATABASE_URL=${DATABASE_URL}
ENV DATABASE_URL=${DATABASE_URL}
ARG TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ENV TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ARG DATABASE_PROVIDER=${DATABASE_PROVIDER}
ENV DATABASE_PROVIDER=${DATABASE_PROVIDER}
ARG EXTERNAL_URL=${EXTERNAL_URL}
ENV EXTERNAL_URL=${EXTERNAL_URL}

WORKDIR /app

COPY ./package.json .

ENV NODE_ENV production
ENV PORT 80
COPY . .

RUN yarn

# Make start script executable
RUN chmod +x scripts/start.sh

EXPOSE 80

CMD ["./scripts/start.sh"]